use_frameworks!

platform :ios, '8.0'

target 'JWBasicFoundation_Example' do
  pod 'JWBasicFoundation', :path => '../'

  target 'JWBasicFoundation_Tests' do
    inherit! :search_paths

    
  end
end
